import type { MockProduct, MockCategory } from "@/types/product";

export const MOCK_CATEGORIES: MockCategory[] = [
  { id: "cat-1", name: "Electronics", iconName: "Laptop", count: 124 },
  { id: "cat-2", name: "Fashion & Apparel", iconName: "Shirt", count: 342 },
  { id: "cat-3", name: "Home & Kitchen", iconName: "Home", count: 89 },
  { id: "cat-4", name: "Beauty & Health", iconName: "Sparkles", count: 156 },
  { id: "cat-5", name: "Sports & Outdoors", iconName: "Bike", count: 72 },
  { id: "cat-6", name: "Books & Stationery", iconName: "BookOpen", count: 43 },
];

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: "prod-1",
    name: "Wireless Noise-Cancelling Headphones",
    description: "Experience premium sound quality with hybrid active noise cancellation, built-in voice assistants, and up to 40 hours of battery life.",
    category: "Electronics",
    categoryId: "cat-1",
    price: 199.99,
    discount: 15,
    stock: 25,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    rating: 4.8,
    reviewsCount: 128,
    sellerName: "Apex Electronics Ltd.",
  },
  {
    id: "prod-2",
    name: "Minimalist Leather Backpack",
    description: "Handcrafted from top-grain leather, this daily commuter bag fits up to a 15-inch laptop and features hidden security pockets.",
    category: "Fashion & Apparel",
    categoryId: "cat-2",
    price: 120.00,
    discount: 0,
    stock: 8,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    rating: 4.5,
    reviewsCount: 42,
    sellerName: "Urban Craft Co.",
  },
  {
    id: "prod-3",
    name: "Smart Fitness Watch Tracker",
    description: "Track your workouts, sleep cycles, blood oxygen levels, and receive smart notifications with a vivid AMOLED touch interface.",
    category: "Electronics",
    categoryId: "cat-1",
    price: 149.50,
    discount: 20,
    stock: 12,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    rating: 4.2,
    reviewsCount: 95,
    sellerName: "Apex Electronics Ltd.",
  },
  {
    id: "prod-4",
    name: "Organic Bamboo Bedsheet Set",
    description: "Breathable, moisture-wicking sheet set woven from sustainable organic bamboo fibers. Silky soft texture, ideal for sensitive skin.",
    category: "Home & Kitchen",
    categoryId: "cat-3",
    price: 89.99,
    discount: 10,
    stock: 15,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80",
    rating: 4.6,
    reviewsCount: 67,
    sellerName: "Earthy Home Concepts",
  },
  {
    id: "prod-5",
    name: "Stainless Steel Gooseneck Kettle",
    description: "Pour-over precision brewing kettle with accurate temperature control dial, ergonomic wooden handle, and triple-layer base.",
    category: "Home & Kitchen",
    categoryId: "cat-3",
    price: 45.00,
    discount: 0,
    stock: 4,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    rating: 4.9,
    reviewsCount: 81,
    sellerName: "Earthy Home Concepts",
  },
  {
    id: "prod-6",
    name: "Ultralight Camping Hammock",
    description: "Heavy-duty paratrooper nylon hammock supporting up to 400 lbs. Folds down to the size of an orange, suspension straps included.",
    category: "Sports & Outdoors",
    categoryId: "cat-5",
    price: 34.99,
    discount: 0,
    stock: 18,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=600&q=80",
    rating: 4.7,
    reviewsCount: 36,
    sellerName: "Nomad Trails Gear",
  },
  {
    id: "prod-7",
    name: "Hydrating Hyaluronic Facial Serum",
    description: "Rejuvenating serum containing multi-molecular weight hyaluronic acid and Vitamin B5. Intense cell hydration and plumping.",
    category: "Beauty & Health",
    categoryId: "cat-4",
    price: 24.50,
    discount: 30,
    stock: 50,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&w=600&q=80",
    rating: 4.4,
    reviewsCount: 110,
    sellerName: "Glow & Co. Cosmetics",
  },
  {
    id: "prod-8",
    name: "Ergonomic Office Mesh Chair",
    description: "Adjustable 3D armrests, dynamic lumbar support support, synchro-tilt controls, and premium breathable mesh back.",
    category: "Home & Kitchen",
    categoryId: "cat-3",
    price: 299.00,
    discount: 10,
    stock: 0, // Out of stock to test low-stock/out-of-stock badges
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&w=600&q=80",
    rating: 4.3,
    reviewsCount: 19,
    sellerName: "Urban Craft Co.",
  },
];
